load('ext://pack', 'pack')

k8s_yaml('kubernetes.yaml')
k8s_resource('nodejs-prototype', port_forwards=3000)
pack('nodejs-prototype-image', buildpacks=[
                                "gcr.io/paketo-buildpacks/nodejs",
                                ],
                                env_vars=['BP_NODE_RUN_SCRIPTS=build'],
                                live_update=[
                                sync('.', '/workspace')
                                ])
