apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: sample-cluster-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/watchexec
  - image: gcr.io/paketo-buildpacks/dotnet-core
  - image: gcr.io/paketo-community/build-plan
