apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-prototype
spec:
  selector:
    matchLabels:
      app: dotnet-prototype
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-prototype
    spec:
      containers:
      - name: dotnet-app
        image: dotnet-prototype-image
        ports:
        - containerPort: 80
        env:
        - name: "PORT"
          value: "80"
