apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-builder
spec:
  tag: harbor-repo.vmware.com/tanzu_desktop/kpack-builder
  serviceAccount: default
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: sample-cluster-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/dotnet-core
